obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#ifndef ODM_HQ_EDIT /* zhangchao@ODM.HQ.Charger 2019/09/4 modified for bring up charging */
#obj-$(CONFIG_OPPO_CHARGER)	+= oppo/
#endif
