ifeq ($(CONFIG_OPPO_FINGERPRINT),y)
obj-y        += oppo_fp_common/
obj-$(CONFIG_MACH_MT6785)        += fpc/
obj-$(CONFIG_MACH_MT6785)        += goodix_fp/
obj-$(CONFIG_MACH_MT6771)        += et512/
obj-$(CONFIG_MACH_MT6771)        += silead_mtk/
obj-$(CONFIG_MACH_MT6768)        += et512/
obj-$(CONFIG_MACH_MT6768)        += silead_mtk/
endif
