obj-$(CONFIG_TOUCHSCREEN_MTK_HIMAX_CHIPSET_SPI) += hxchipset/
#obj-$(CONFIG_TOUCHSCREEN_MTK_NT36xxx_HOSTDL_SPI) += nvt_driver/

# ifdef ODM_HQ_EDIT
# liunianliang@ODM.BSP.TP 2020/02/17, Add for oppo6771 Tp driver.
obj-$(CONFIG_TOUCHSCREEN_NT36525)  += nt36525/
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) += ipio_touch_driver-v1.0.3.8/
# endif