#
# Copyright (C) 2015 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

##ifdef ODM_HQ_EDIT
## zuoqiquan@ODM.BSP.Sensor  2019/09/06 bring up nfc 
obj-$(CONFIG_NFC_CHIP_PN553) += pn553/
##endif /*ODM_HQ_EDIT*/